version: '3.9'

services:
  nginx:
    container_name: NGINX
    build:
      dockerfile: ./requirements/nginx/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./requirements/wordpress/wordpress
        target: /var/www/wordpress
      - type: bind
        source: ./requirements/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      # - '443:443'
       - '8080:80'
    depends_on:
      - php

  php:
    container_name: WordPress
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./requirements/wordpress/wordpress
        target: /var/www/wordpress
      - type: bind
        source: ./requirements/wordpress/php-fpm.conf
        target: /etc/php/7.4/fpm/php-fpm.conf
    expose:
      - 9000
    depends_on:
      - db

  db:
    container_name: DB
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
      context: .
    volumes:
      - type: volume
        source: WordPress-database-volume
        target: /var/lib/mysql
      # - type: bind
      #   source: ./requirements/mariadb/init.sql
      #   target: /docker-entrypoint-initdb.d
      # - type: bind
      #   source: ./requirements/mariadb/
    environment:
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress

volumes:
   WordPress-database-volume: