services:
  nginx:
    container_name: nginx
    build:
      dockerfile: ./requirements/nginx/Dockerfile
      context: .
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - '443:443'
    depends_on:
      - php
    restart: always
    networks:
      - inception

  php:
    container_name: wordpress
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
      context: .
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ./.env
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - inception

  db:
    container_name: mariadb
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
      context: .
    image: mariadb
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      interval: 20s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env
    networks:
      - inception

volumes:
   mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/resaito/data/mariadb

   wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/resaito/data/wordpress

networks:
  default:
    driver: bridge
  inception:
    name: inception
