# version: '3'

services:
  nginx:
    container_name: NGINX
    build:
      dockerfile: ./requirements/nginx/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./requirements/wordpress/wordpress
        target: /var/www/wordpress
    ports:
      # - '443:443'
       - '8080:80'
    depends_on:
      - php

  php:
    container_name: WordPress
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./requirements/wordpress/wordpress
        target: /var/www/wordpress
    env_file:
      - ./.env
    expose:
      - 9000
    depends_on:
      - db

  db:
    container_name: DB
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
      context: .
    volumes:
      - type: volume
        source: WordPress-database-volume
        target: /var/lib/mysql
      # - type: bind
      #   source: ./requirements/mariadb/init.sql
      #   target: /docker-entrypoint-initdb.d
      # - type: bind
      #   source: ./requirements/mariadb/
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
   WordPress-database-volume: